### ISSUE TITLE
update deprecated biopython functions

### ISSUE THREAD

**Issue by tturowski** [zstephens/neat-genreads#104]
Using biopython 1.79 and higher raise error:
AttributeError: 'Seq' object has no attribute 'tomutable'
and
AttributeError: 'MutableSeq' object has no attribute 'toseq'

to solve it four replacements are needed in SequenceContainer.py according to the biopython note:
Instead of myseq.tomutable() or mymutableseq.toseq(), you should now use
Bio.Seq.MutableSeq(myseq) or Bio.Seq.Seq(mymutableseq), respectively.

**Comment by joshfactorial** [comment]
Please use our most up to date repo at GitHub.com/NCSA/neat or downgrade to an older version of biopython for this repo.
