### ISSUE TITLE
Possible Error

### ISSUE THREAD

**Issue by muppetjones** [zstephens/neat-genreads#12]
In `genReads.py` ~ line `764-766`
```python
                    if myChr not in inputRegions:
                        mutRateRegions[myChr] = [-1]
                        mutRateValues[myChr] = [0.0]
```
I think `inputRegions` is supposed to be `mutRateRegions`.

**Comment by zstephens** [comment]
That would be correct! A slick bug-catch on a very rarely tested branch of the code.

Much appreciated!


On Oct 17, 2016, at 5:47 PM, Stephen J Bush <notifications@github.com<mailto:notifications@github.com>> wrote:


In genReads.py ~ line 764-766

                    if myChr not in inputRegions:
                        mutRateRegions[myChr] = [-1]
                        mutRateValues[myChr] = [0.0]

I think inputRegions is supposed to be mutRateRegions.
