### ISSUE TITLE
-t targeted region bed file doesn't work

### ISSUE THREAD

**Issue by baohua100** [zstephens/neat-genreads#16]
python genReads.py -r hg19.fa -R 150 -c 3000 -t target.bed -o sim1_norm --bam --vcf --pe 350 30

The program was still trying to sample all reads from the genome, but not limited to the target.bed regions.

**Comment by zstephens** [comment]
Greetings,

When given a bed file of targeted regions, by default NEAT will sample a majority of the reads from that region, and a fraction of reads from outside the region. This is controlled by the input parameter “-to”, which is 0.02 by default (meaning regions outside the specified regions will be sampled from with probability 2%). By setting -to 0.0 you should able to restrict read sampling to entirely within targeted regions.

Hope this helps!
Zach


On Dec 30, 2016, at 3:24 PM, baohua100 <notifications@github.com<mailto:notifications@github.com>> wrote:


python genReads.py -r hg19.fa -R 150 -c 3000 -t target.bed -o sim1_norm --bam --vcf --pe 350 30

The program still trying to sampling all reads from the genome, but not limited to the target.bed regions.
