### ISSUE TITLE
Missing trinucleotide frequency key if none found [neat-genreads/utilities/genMutModel.py]

### ISSUE THREAD

**Issue by mrweber2** [zstephens/neat-genreads#17]
Hi Zach,

I recently noticed that when a trinucleotide mutation (in this case, GAT->GCT) is not found in the sample, that key is not included in the dictionary. Does this sound like an easy fix? Do we need to draw keys from a hard-coded list of 192, or is there a more efficient way to solve this?

Thanks,
Matt

**Comment by zstephens** [comment]
I updated genMutModel such that trinucleotides not encountered in the data are given mutation probability 0.
