### ISSUE TITLE
ZeroDivisionError when specifying -to option to be 0

### ISSUE THREAD

**Issue by sbbundho** [zstephens/neat-genreads#18]
Hello Zach, 

I was generating simulated reads using the following command:
"python /u/sbundhoo/neat-genreads/genReads.py -r /.mounts/labs/PDE/data/reference/hg19/fasta/UCSC/chr21.fa -R 101 -o /scratch2/users/sbundhoo/02_02 --bam --vcf --gz --pe 300 30 -c 50 -to 0-t /u/sbundhoo/bed_files/sorted_offtarget500b_chr21_all.bed"

However, when I specify -to to 0, I get an error as such:
"ZeroDivisionError: float division by zero"

Isn't the off-target coverage option supposed to work with 0 as the argument? 

Thanks, 

Shaheen

**Comment by zstephens** [comment]
Greetings,

Thanks for catching this! It is indeed supposed to work with -to 0, but an oversight caused that div-by-zero error. I believe I fixed it, let me know if you run into anything else.

Thanks!
Zach
