### ISSUE TITLE
Error while generating Tumor Normal Pair 

### ISSUE THREAD

**Issue by sbbundho** [zstephens/neat-genreads#19]
Hello Zach, 

I was trying to generate some tumor normal pair using your suggested method provided in the tutorial.  I used the same script with the slightest changes(including file names, directories, pathnames etc).  However, I am running into the following error: (copied from error log file)

> Traceback (most recent call last):
  File "neat-genreads/genReads.py", line 150, in <module>
    MUT_MODEL = parseInputMutationModel(MUT_MODEL,1)
  File "/u/sbundhoo/neat-genreads/py/SequenceContainer.py", line 725, in parseInputMutationModel
    outModel[8][i][j][l] /= float(sum(outModel[8][i][j]))
ZeroDivisionError: float division by zero

When I ran the script with the files you provided in the tutorial folder, it seems to work fine though.  I am not sure what may be causing this error. 

Thanks, 

Shaheen

**Comment by zstephens** [comment]
I believe I fixed this. It had to do with the case when a particular trinucleotide mutation is not present in the input mutation model, but was expected to be.

Let me know if you run into further issues.
