### ISSUE TITLE
Monoploid issues with VCF

### ISSUE THREAD

**Issue by jrkirk61** [zstephens/neat-genreads#23]
Hi,

I was trying to run genReads.py and provided it with a VCF to add in variants. I also specified that this is a monoploid genome. None of my variants were present in the output. I then tried adjusting my VCF to have two alleles, and then set the ploidy to diploid. In this case, the variants were present in the output. So there seems to be something wrong with the monoploid settings and how it pulls in variants from a VCF file.

Thanks,
Jessica

**Comment by zstephens** [comment]
This one slipped through the cracks. Sorry for such a long delay (I'm sure you've pursued an alternative at this point), but I believe I fixed this.

Thanks for the report!
