### ISSUE TITLE
The parameter setting

### ISSUE THREAD

**Issue by phoebee-h** [zstephens/neat-genreads#26]
Thank you so much for the prompt reply!

I'd also like to ask:

(1) Why is the read length in the "Usage" description different from the command line? Is it a typo or a tricky thing I should be cautious dealing with?
For example, I want to set read length with 150 bps, but in the command line -R should be 151?
![image](https://user-images.githubusercontent.com/28743573/28764685-642a5442-75f9-11e7-9753-f3727098b46d.png)

(2) After generating the sequence with this command, I got the golden VCF:
`python genReads.py -r chr21.fa -R 150 -o /home/phoebe/neat-genreads/0728_chr21_simulated --bam --vcf --pe 300 30`

What does the WP in the column INFO stand for?

![image](https://user-images.githubusercontent.com/28743573/28764741-ab59c7bc-75f9-11e7-99e1-93aa46882779.png)

**Comment by zstephens** [comment]
Greetings!

Thanks for catching the typo in the readme, both of them should've been the same number (in this case, 101). Additionally, I added a description of the WP field to the output VCF header.

The WP flag is used internally by genReads to determine which set of chromosomes to insert mutations on (WP stands for "which ploid"). Basically it gives you phasing information, for human (diploid) the possible values are WP=0 (occurs on first chromosome, so a heterozygous variant), WP=1 (occurs on the other chromosome, also heterozygous) or WP=0,1 (occurs on both chromosomes, so homozygous).

Hope this helps!

**Comment by phoebee-h** [comment]
Thanks, Zack!
So 0 or 1 just stands for the ploid instead of the varaints occurs or not (0= none, 1 = variant)?
I'm confused by these two for explaining them.
WP = 1/0
WP = 0/1 
Are there any differences?

**Comment by zstephens** [comment]
The index of the zeros and ones indicate which chromosome copy the mutation is present on. Basically it provides phasing information. For example, if we were simulating triploid data:

WP=1/0/0 would indicate a mutation on the first chromosome copy only (so expected allele fraction in the alignment would be ~33%)
WP=0/0/1 would indicate a mutation on the third chromosome copy only
WP=1/1/0 first and second copy (so expected allele fraction ~66%)
WP=1/1/1 present in every chromosome copy (AF=100%)

Hope this helps!
