### ISSUE TITLE
Reversed base qualities in the second generated FASTQ file

### ISSUE THREAD

**Issue by bmscicho** [zstephens/neat-genreads#33]
Hello,

I've performed reads generation on a sample data coming from https://github.com/slzhao/QC3#sExample.

I have used two FASTQ files (`3_1.example.fastq`, `3_2.example.fastq`) and a BAM file `3.example.bam`. I want to generate paired-end data.

I have used the following utils to provide additional models for the generation:
- `computeFraglen.py`
- `genSeqErrorModel.py` (providing both FASTQ files using `-i` and `-i2` options)

Then, I've run FastQC on both input and output (generated) files.
For the first generated FASTQ file, results were quite similar to the original FASTQ file.
Although, for the second generated FASTQ file, the quality values seem to be reversed (with regard to position in read), see the attached FastQC graphs below:

Original:
![reversed_base_qualities_in_the_second_generated_fastq_file_original](https://user-images.githubusercontent.com/10560788/36485279-b6200e7a-1713-11e8-8924-1bf53913bad2.png)
Generated:
![reversed_base_qualities_in_the_second_generated_fastq_file_generated](https://user-images.githubusercontent.com/10560788/36485259-a8611338-1713-11e8-8bde-fd217349cf6f.png)

Is it a bug in neat-genreads? Or is this behavior expected? Am I missing some knowledge about how R2 reads are stored?

**Comment by jrkirk61** [comment]
Just commenting to say I also see this when I run the command:

```
python genReads.py -r Cal07_ref_400-599.fasta \
-R 250 -o 5DI-perSegment/400-499_DIs -e error-model/1A-250-error-model.p \
-p 1 -M 0 -v VCF/400-499_DIs.vcf --pe 315 15 --bam --vcf -c 50000
```
The "read2" or reverse reads are demonstrating reversed quality scores, like in the example above. This is definitely not natural or normal. I agree with @bmscicho that the quality score seems to be flipped in the reverse reads. For example, position 76 (above) should have the quality score of position 1, and vice versa.

**Comment by afzm** [comment]
I also see this, anything to overcome this? I will have to use another simulator...

**Comment by zstephens** [comment]
Greetings. I just pushed a fix for this, so FQ output should now look as expected. I need to simulate some BAMs as well to ensure everything looks as it should.

Cheers.

**Comment by afzm** [comment]
Thank you!! This simulator is one of the easiest to use and is great that that feature is corrected!! Cheers
