### ISSUE TITLE
Parsing errors with samtools

### ISSUE THREAD

**Issue by JustinChu** [zstephens/neat-genreads#35]
when using the `--bam` options I keep getting the following error with the resultant file:
```
[E::bam_read1] CIGAR and query sequence lengths differ for simulatedReads-FN677756.1-74597/1
```
on samtools 1.6

I'm pretty sure this is a recent thing because it seems to work before, but maybe on another version of samtools.

**Comment by jrkirk61** [comment]
I am also seeing this error with samtools 1.7. At some point when using `samtools view`, it will stop and return the following:

```
[E::bam_read1] CIGAR and query sequence lengths differ for 400-499_DIs-PB2-880825/2
[main_samview] truncated file.
```

**Comment by zstephens** [comment]
Greetings, would you be able to share the specific commands you used to generate the data? I was unable to reproduce this on my test datasets, so if you could share the parameters that would be helpful.

Thanks!

**Comment by jrkirk61** [comment]
Here is the command I used: `samtools view -h 400-499_DIs_golden.bam > 400-499_DIs_golden.sam`

When I switched to samtools 1.5 this ran without problems. Here is the read that caused problems with samtools 1.7:

`400-499_DIs-PB2-880825/2	147	PB2	84	70	124M1D50M1868D62M1D12M	=	8	-326	CACTGTGGACCATATGGCCATAATCAAAAAGTACACATCAGGAAGGCAAGAGAAGAACCCCGCACTCAGAATGAAGTGGATGATGGCAATGAGATACCCAATTACAGCAGACAAGAGAATAATGACATGATTCCAGAGAGGAATGAACAAGGACAAACCCTCTGGAGCAAAACATGGCCCAGCATTAAGCATCAATGAACTGAGCAATCTTGCAAAAGGAGAGAAGGCTAATGTGCAATTGGGCAAGGGG	BBAAAFFFFFFFGGGGGGGGGGHHHHHGHHHHHHHHGGGHHHHHHHHHHHHHHHHHHHHGGGFHHGGHHHHGHHGGGG22210E3BBF23GGGGHHGHHHHHHHHGGGHGGGHFBGGHHH?//</@1?/11>2<E1>//EG1@FGFHHHHHHHHHGFGHHHHHHHHHHHHHHHHHGHHHHHFFHHHHHHGFHFHHGFGHBGHHHHHHHHHHHFFFFFFFDFFEGG<0CFGGHHGGE/;BFFFF9-9FBCF`

As you can see, it had a pretty complicated CIGAR string.

**Comment by jrkirk61** [comment]
Also, here is what I used to generate this dataset:

```
python genReads.py -r Cal07_ref_400-599.fasta \
-R 250 -o 5DI-perSegment/400-499_DIs -e error-model/1A-250-error-model.p \
-p 1 -M 0 -v VCF/400-499_DIs.vcf --pe 315 15 --bam --vcf -c 500000
```

The VCF contains large structural deletions.

**Comment by afzm** [comment]
I encounter the same error. Simulation step:

`genReads.py -r /home/A_thaliana.TAIR10.fa  -o /home/ -R 150 --pe 500 2 -c 150 -M 0 --vcf --bam`

When trying to convert the golden.bam to .sam:
```
samtools view -h -o golden.sam golden.bam

[E::bam_read1] CIGAR and query sequence lengths differ for golden dna:chromosome chromosome:TAIR10:1:1:30427671:1 REF-41489/2
[main_samview] truncated file.
```

**Comment by thon-deboer** [comment]
I also run into this issue

**Comment by thon-deboer** [comment]
Here's an example of a CIGAR string that is not correct...

`ecoli-chr-268539/1      99      chr     2726091 70      14M1D25M1D60M   =       2726314 324     CCGGCTCGACCAGTAGCTATTACGCTTTCTTTAAATGATGCTGCTTCTAAGCCAACATCCTGGCTGTCTGGGCCTTCCCACATCGTTTCCCACTTAACCAT   GDG%GFFGGFFEG#,FFGGG#G81EG>GGGGGGGGEGGA/GFFF3GGGEGFDDGFGFGE9GDGDBC@G@G;GGGFGFCGFGFEGGFGF8F<>GGDAF1<DF`

When you add up the CIGAR string matching bases, you come to 14+25+60 = 99 while there are 101 bases.

I'm guessing this has to do with the DOUBLE deletions that are represented in the CIGAR string.
Deletions do not add to the total length of a CIGAR string but in this case they DO need to be counted to come to 101.
Normally in neat, this is done correctly for single deletions, but I am guessing it does not happen correctly for more than ONE deletion that is not consecutive...

**Comment by thon-deboer** [comment]
I figured out how to fix this issue...
SequenceContainer.py resets extraCigarVal to be empty inside the "for error" loop so it resets it each time it finds a Deletion, but it should only reset it outside the for error loop, so it maintains the extra CIGAR values for a read if it contains more than one deletion.

Tried to commit the fix, but I don't have permissions...

**Comment by zstephens** [comment]
thanks, much appreciated!
