### ISSUE TITLE
Bug in vcf-only generation

### ISSUE THREAD

**Issue by bmscicho** [zstephens/neat-genreads#37]
The following bug is present in 5b8bc84ddd3b7bd32b425cb5dd5245bf854148db.

I want to generate a VCF file only. I am using the following command:

```
python $NEAT2_PATH/genReads.py -r "$HG38_CHR1" -R 50 -c 1 -o "$WORKDIR/common-vcf/" -t "$TARGET_BED" -to 0 --no-fastq --vcf --rng 0
```

The reference sequence is chr1 from HG38.
Target BED content is as follows: `chr1	10021	914744	1.797693135e+308	0	0`

I get a "variable referenced before assignment" error:

```
Only producing VCF output, that should speed things up a bit...
Using default sequencing error model.
Warning: Read length of error model (101) does not match -R value (50), rescaling model...
Using default gc-bias model.
Bypassing FASTQ generation...
found index ...
reading chr1... 60.868 (sec)
--------------------------------
generating vcf...
Traceback (most recent call last):
  File ".../neat-genreads2-wip/genReads.py", line 789, in <module>
    main()
  File ".../neat-genreads2-wip/genReads.py", line 616, in main
    if sum(coverage_dat[2]) >= LOW_COV_THRESH:
UnboundLocalError: local variable 'coverage_dat' referenced before assignment
```

**Comment by bmscicho** [comment]
The `coverage_dat` variable is initialized as follows (lines 522-524 of genReads.py):

```
if ONLY_VCF == False:

	coverage_dat = [GC_WINDOW_SIZE,GC_SCALE_VAL,[]]
```
So it is not initialized if there's only VCF to generate, but it is used later (in line 616).

**Comment by zstephens** [comment]
Greetings, thanks for reporting this!

I believe I fixed this. That section of code needs to be run regardless of ONLY_VCF or not, so I removed that conditional.

Thanks!
-Zach
