### ISSUE TITLE
Is there a galaxy tool-shed version of this somewhere?

### ISSUE THREAD

**Issue by thon-deboer** [zstephens/neat-genreads#39]
I really like to be able to use your tool inside of Galaxy, but before I embark on doing a custom install, I was wondering if there is a version already out there.

Tried the usual places (tool-shed, google) but did not find anything so guessing I should start embarking?

**Comment by zstephens** [comment]
Greetings,

I'm not too familiar with Galaxy, and haven't installed NEAT over there or anything. But I'm happy to hear it could be useful for your applications.

So feel free to embark, and if you have any questions regarding input options or other technical bits feel free to ask. Good luck!

**Comment by thon-deboer** [comment]
Thanks...I have embarked and will let you know when it is up on the toolshed...
Did find small discrepancy between tool arguments and the documentation here...(-Mb is not defined and -e is defined but not in the tool)
