### ISSUE TITLE
Exact Coverage 

### ISSUE THREAD

**Issue by danablanc** [zstephens/neat-genreads#51]
Hi,

How can I determine the exact coverage and no the average one using your tool?

Thanks for your attention!

**Comment by zstephens** [comment]
Greetings, can you clarify what you mean? Would you like the coverage to be more constant than it is with default GC% bias models? If that's what you mean I would be able to add an input argument that ignores the GC bias.

If you want the coverage to be identical at every position I don't think that is possible with the way the code currently works.

-Zach

**Comment by zstephens** [comment]
added "--force-coverage" input option in 2ea9720b6683aa1e1a84d206223219414302e810 which causes NEAT to ignore gc-bias and targeted capture regions. positional coverage will still fluctuate due to randomness in coordinate sampling.
