### ISSUE TITLE
Recommendation for SyntaxError: Missing parentheses in call to 'print' . (Python 3)

### ISSUE THREAD

**Issue by LindoNkambule** [zstephens/neat-genreads#52]
Hi,

Just a recommendation: don't you think it'd be a good idea to update the genReads.py and mergeJobs.py scripts so that it takes into consideration those using Python 3? If you include parentheses, the script would still work in Python 2. 

Thank you.

**Comment by meridith-e** [comment]
Hi! This was very long ago, but we are now updating NEAT to Python 3 standards.
