### ISSUE TITLE
UnboundLocalError: local variable 'havePrinted100' referenced before assignment

### ISSUE THREAD

**Issue by DTNeil** [zstephens/neat-genreads#53]
Hi,
When I run the following line:
>  python genReads.py -r test1.fa -R 101 -o test3.fq --bam --vcf --pe 300 30
I receiving this error:
UnboundLocalError: local variable 'havePrinted100' referenced before assignment
I already looked at other answers and can't seem to fix this.

**Comment by zstephens** [comment]
I pushed a quick fix that should prevent this error.

This should seemingly only happen if the reference sequence does not have any regions of sufficient size that the simulator can sample reads from. Is test1.fa a very short sequence?
