### ISSUE TITLE
Simulation of fixed read numbers (incl. low coverage)

### ISSUE THREAD

**Issue by tloka** [zstephens/neat-genreads#63]
Hello,

I was wondering if it would be possible to add a parameter that allows to simulate a fixed number of reads instead of a coverage (e.g., 1M reads)!?

Addditionally, I was wondering about the LOW_COV_THRESH = 50 in your code.
Do I understand it correctly that regions with a calculated coverage below 50 are not covered at all? Wouldn't this be in conflict with the default coverage of 10? What would be the effect of setting even lower coverage for simulation, e.g. <1, which can be useful for the construction of metagenomic samples?
I have the feeling that I got something wrong here ...

**Comment by zstephens** [comment]
Greetings!

The units for LOW_COV_THRESH is closer to "# of bases sampled" than "x coverage". I.e. if a window of the genome currently being sampled from is estimated to yield less than 50bp of sequence (less than 1 read in nearly every use case) then it will be skipped. This is mostly to speed up the performance of the simulation when using a sparse BED file of target regions.

Coverage can be any positive float. I haven't thoroughly tested how low you can go, but for values <1 it should behave as expected:

`python genReads.py -R 101 --pe 300 30 -c 0.1 -r chr1_subset.fa -o lowCovTest --bam`

<img width="509" alt="Screen Shot 2019-08-07 at 2 33 26 PM" src="https://user-images.githubusercontent.com/8508373/62652707-95374f00-b921-11e9-9b09-06b8d050f870.png">

# non-N ref bases: 361380
# bases sampled: 185*2*101 = 37370
empirical coverage: 0.103x


As per the initial question, it would be non-trivial to output a fixed number of reads. There are many probabilistic elements that determine where the reads will be sampled from (GC%-bias, BED target regions, PE fragment length distributions), and it's difficult to know how it will shake out across the entire reference sequence as it's being processed window-by-window. The best suggestion I could offer at the moment would be to choose an input coverage value that is expected to yield approximately 1M reads. In the above example that would be `-c 559` 
 = (1M*2*101)/361380

**Comment by tloka** [comment]
Thanks for your very quick reply and the detailed explanation, it became clear to me now (although, I still find the naming of LOW_COV_THRESH a bit misleading).

Yeah, I already had the feeling that the sampling approach could be problematic to simulate a fixed number of reads. I will probably simulate using a slightly higher coverage and reduce the number of simulated reads outside of neat as a workaround.
Thanks again for your quick answer!
