### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1.0086e+06'

### ISSUE THREAD

**Issue by schmeing** [zstephens/neat-genreads#66]
Hi,
for another genome I got this error during GC bias computation:
```
Traceback (most recent call last):
  File "utilities/computeGC.py", line 78, in <module>
    currentCov  += int(splt[2])
ValueError: invalid literal for int() with base 10: '1.0086e+06'
```
This should be easy to fix, large values seem to be written in float notation from `bedtools genomecov`, so computeGC should read in floats there.

Thanks

**Comment by zstephens** [comment]
Good catch! Fixed in https://github.com/zstephens/neat-genreads/commit/9ea1e225f0e19b68ca2f7fe145d7879d3fad421d
