### ISSUE TITLE
Sequencing error rate for long reads not as specified

### ISSUE THREAD

**Issue by reinator** [zstephens/neat-genreads#78]
Hi! 
I specified to simulate long reads (15kb) with an error-rate (-E) of 0.10. Correct me if I am wrong, but I was expecting to obtain reads with a mean quality of Q10 (which is the representation for 0.10 probability of error).
When I run FastQC, the mean quality for my reads is up to Q30, as the image shows.
![image](https://user-images.githubusercontent.com/5761537/88743693-afae9d80-d11b-11ea-9a81-286b0ca9e6da.png)

Any possible explanation?

**Comment by zstephens** [comment]
Greetings!

For some reason I had decided that when you rescale the error rates that it does not correspondingly rescale the quality scores. I can't remember why I did this. In the very least I'll add an option to facilitate this. Stay tuned!

**Comment by zstephens** [comment]
added "--rescale-qual" input option in commit 3c83f1e64bbc39159628f4ad8a56f58bd6399fcb, which when used will rescale quality scores by the same multiplier specified via -E.

Feel free to reopen this issue if it doesn't work as expected.
