### ISSUE TITLE
Standard deviation of coverage

### ISSUE THREAD

**Issue by TMiguelT** [zstephens/neat-genreads#82]
**Is your feature request related to a problem? Please describe.**
I would like to be able to know the coverage SD used in the simulator, and ideally customize it myself.

**Describe the solution you'd like**
Perhaps a `-csd DEVIATION` flag, or perhaps add another argument to `-c` such that you can `-c MEAN,SD`

**Describe alternatives you've considered**
Using the current method, which means not knowing the variance of the distribution being used to sample coverage levels.

**Comment by joshfactorial** [comment]
At the moment, this is out of our scope, but we will keep it in mind as a future improvement.
