### ISSUE TITLE
Null Sequencing Error Model

### ISSUE THREAD

**Issue by cilliannolan** [zstephens/neat-genreads#84]
Hello,

I am attempting to create a test dataset without any sequencing error, to compare behaviour between NEAT and other read sequencing simulators. I was hoping to get advice on how to achieve this.

Currently I am running NEAT with the argument "-e 0",  will this result in fastq files without any sequencing error?

Kind regards,
Cillian

**Comment by zstephens** [comment]
To get reads with no sequencing errors you can specify ```-E 0```. Quality scores will still be generated according to the specified model (via ```-e```, or the default model if omitted), but no actual errors will be introduced. If you wish to rescale the quality scores to match the actual error likelihoods (which is this case would be a constant string of the highest possible Q-score, presumably) you can add the ```--rescale-qual``` input option.

**Comment by zstephens** [comment]
Hope this ended up working. Feel free to reopen this if it doesn't work as expected.
