### ISSUE TITLE
Simulate SNPs only without indels 

### ISSUE THREAD

**Issue by aaronkwc** [zstephens/neat-genreads#87]
Hi.

I wonder if neat-genreads can simulate SNPs only and not do indels when using -M ? I tried using the pickle file from genReads1/models/mutModel_allSNP.p but it gave me the following error:

`Traceback (most recent call last):
  File "/home/aaronkwc/neat-genreads/genReads.py", line 154, in <module>
    MUT_MODEL = parseInputMutationModel(MUT_MODEL,1)
  File "/home/aaronkwc/neat-genreads/py/SequenceContainer.py", line 841, in parseInputMutationModel
    outModel[0] = pickle_dict['AVG_MUT_RATE']
TypeError: list indices must be integers, not str`

command used:
`python ~/neat-genreads/genReads.py \
                -r hg19.fasta \
                -R 126 \
                -c 300 \
                -o sim_bamv3/test \
                -v mutations.vcf \
                -M 0.1 \
                -m mutModel_allSNP.p \
                -E 0.05 \
                --bam \
                --vcf \
                --pe 300 30 \
                --no-fastq
`

It worked perfectly fine without -m, but I did not want the random indels. Is there anything wrong with the options used? If not, are there any workarounds for this feature? Thanks a lot!!

**Comment by zstephens** [comment]
Greetings, I added a new mutation model to the repository which has an indel frequency of 0%

models/MutModel_NA12878_noIndel.p

Hope this helps!
