### ISSUE TITLE
Bam input into compute_fraglen.py measures read length rather than insert size

### ISSUE THREAD

**Issue by jeffpbruce** [zstephens/neat-genreads#91]
**Describe the bug**
If a bam file is input directly into compute_fraglen.py without prior conversion to a .sam, the output pickle file appears to contain a model describing the read length rather than the insert size. I used this method because the command described in the readme (`./samtools view toy.bam | python compute_fraglen.py`) yielded the following error:

```
usage: compute_fraglen.py [-h] -i input -o output
compute_fraglen.py: error: the following arguments are required: -i, -o
```

**To Reproduce**
` python compute_fraglen.py -i file.bam -o fraglen`

**Expected behavior**
A a model of the insert size.  What we receive instead is a model of the read length.

**Desktop (please complete the following information):**
 - OS: CentOS Linux 7 (Core)
 - Python v3.7.2
 - pysam v0.15.2
 - samtools v1.10

**Comment by joshfactorial** [comment]
You're correct that the readme was incorrect. I have updated that. We're shifting the NEAT repository to an NCSA owned repo, which you can find here: https://github.com/ncsa/neat-genreads/issues/1. I recreated this issue there and will work on solving it there.
