### ISSUE TITLE
Identical forward and reverse sequences for half of the reads in FASTQ files

### ISSUE THREAD

**Issue by Accio** [zstephens/neat-genreads#98]
**Describe the bug**
In half of the pair-end reads in the FASTQ files, forward and reverse read sequences are identical. This is (correctly) not observed in the golden BAM file.

**To Reproduce**
I created a github repo to describe the issue with a minimal reproducible example: https://github.com/Accio/NEAT-issue

**Expected behavior**
Forward and reverse sequences in the FASTQ files should be distinct, and 100% mapped to the input genome.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joshfactorial** [comment]
I encourage you to visit our most up-to-date repo for this code: https://github.com/ncsa/NEAT - We have identified and fixed this bug. I may pull those changes back to this repo.
